const games = [
  {
    id:"aventura-pixel",
    title:"Aventura Pixel",
    console:"SNES",
    description:"Explore um mundo retrô cheio de desafios, inimigos e segredos.",
    icon:"🗡️",
    colors:["#174b35","#101e46"],
    year:"1994",
    genre:"Aventura",
    developer:"RetroPlay Studio",
    featured:true,
    added:6
  },
  {
    id:"corrida-turbo",
    title:"Corrida Turbo",
    console:"Mega Drive",
    description:"Velocidade, curvas perigosas e pistas inspiradas nos anos 1990.",
    icon:"🏎️",
    colors:["#7a1f2c","#2b163e"],
    year:"1993",
    genre:"Corrida",
    developer:"Pixel Motors",
    featured:true,
    added:5
  },
  {
    id:"pocket-quest",
    title:"Pocket Quest",
    console:"Game Boy",
    description:"Uma pequena aventura portátil com exploração e mistérios.",
    icon:"🧙",
    colors:["#536b2d","#24351d"],
    year:"1992",
    genre:"RPG",
    developer:"Green Pocket",
    featured:true,
    added:4
  },
  {
    id:"arena-64",
    title:"Arena 64",
    console:"Nintendo 64",
    description:"Batalhas tridimensionais em arenas cheias de obstáculos.",
    icon:"⚔️",
    colors:["#5c2570","#17244d"],
    year:"1998",
    genre:"Ação",
    developer:"Polygon Works",
    featured:true,
    added:3
  },
  {
    id:"racer-one",
    title:"Racer One",
    console:"PlayStation",
    description:"Corridas noturnas com carros rápidos e visual clássico.",
    icon:"🌃",
    colors:["#313b73","#4b152e"],
    year:"1997",
    genre:"Corrida",
    developer:"Night Drive",
    featured:false,
    added:2
  },
  {
    id:"galaxy-defender",
    title:"Galaxy Defender",
    console:"Arcade",
    description:"Proteja a galáxia em ondas cada vez mais difíceis.",
    icon:"🚀",
    colors:["#0e5d67","#251741"],
    year:"1989",
    genre:"Nave",
    developer:"Arcade Labs",
    featured:true,
    added:1
  }
];
