-- RetroPlay Conta 2.0
-- Execute UMA VEZ no Supabase: SQL Editor > New query > cole tudo > Run.
-- Cria progresso de jogos e histórico online com segurança por usuário.

begin;

create table if not exists public.player_game_activity (
  user_id uuid not null references auth.users(id) on delete cascade,
  game_id text not null,
  game_name text not null,
  game_console text not null default 'Console',
  game_cover text not null default '',
  started_count integer not null default 0 check (started_count >= 0),
  first_played_at timestamptz not null default now(),
  last_played_at timestamptz not null default now(),
  completed_at timestamptz,
  primary key (user_id, game_id)
);

create index if not exists player_game_activity_last_played_idx
  on public.player_game_activity (user_id, last_played_at desc);
create index if not exists player_game_activity_completed_idx
  on public.player_game_activity (user_id, completed_at desc)
  where completed_at is not null;

create table if not exists public.player_online_matches (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  game_id text not null,
  game_name text not null,
  game_console text not null default 'Console',
  game_cover text not null default '',
  opponent_name text not null default 'Rival',
  result text not null check (result in ('win', 'loss', 'draw')),
  room_code text not null default '',
  played_at timestamptz not null default now()
);

create index if not exists player_online_matches_user_date_idx
  on public.player_online_matches (user_id, played_at desc);
create index if not exists player_online_matches_user_result_idx
  on public.player_online_matches (user_id, result);

alter table public.player_game_activity enable row level security;
alter table public.player_online_matches enable row level security;

drop policy if exists "Jogador le o proprio progresso" on public.player_game_activity;
create policy "Jogador le o proprio progresso"
  on public.player_game_activity for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Jogador cria o proprio progresso" on public.player_game_activity;
create policy "Jogador cria o proprio progresso"
  on public.player_game_activity for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Jogador atualiza o proprio progresso" on public.player_game_activity;
create policy "Jogador atualiza o proprio progresso"
  on public.player_game_activity for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Jogador apaga o proprio progresso" on public.player_game_activity;
create policy "Jogador apaga o proprio progresso"
  on public.player_game_activity for delete
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Jogador le as proprias partidas" on public.player_online_matches;
create policy "Jogador le as proprias partidas"
  on public.player_online_matches for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Jogador registra a propria partida" on public.player_online_matches;
create policy "Jogador registra a propria partida"
  on public.player_online_matches for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Jogador atualiza a propria partida" on public.player_online_matches;
create policy "Jogador atualiza a propria partida"
  on public.player_online_matches for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Jogador apaga a propria partida" on public.player_online_matches;
create policy "Jogador apaga a propria partida"
  on public.player_online_matches for delete
  to authenticated
  using (auth.uid() = user_id);

grant select, insert, update, delete on public.player_game_activity to authenticated;
grant select, insert, update, delete on public.player_online_matches to authenticated;
grant usage, select on sequence public.player_online_matches_id_seq to authenticated;

create or replace function public.retroplay_record_game_start(
  p_game_id text,
  p_game_name text,
  p_game_console text default 'Console',
  p_game_cover text default ''
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_game_id text := left(trim(coalesce(p_game_id, '')), 100);
begin
  if v_user is null then
    return false;
  end if;
  if length(v_game_id) = 0 then
    raise exception 'GAME_ID_REQUIRED';
  end if;

  insert into public.player_game_activity (
    user_id, game_id, game_name, game_console, game_cover,
    started_count, first_played_at, last_played_at
  ) values (
    v_user,
    v_game_id,
    left(trim(coalesce(p_game_name, v_game_id)), 160),
    left(trim(coalesce(p_game_console, 'Console')), 80),
    left(trim(coalesce(p_game_cover, '')), 500),
    1,
    now(),
    now()
  )
  on conflict (user_id, game_id) do update
  set game_name = excluded.game_name,
      game_console = excluded.game_console,
      game_cover = excluded.game_cover,
      started_count = public.player_game_activity.started_count + 1,
      last_played_at = now();

  return true;
end;
$$;

create or replace function public.retroplay_set_game_completed(
  p_game_id text,
  p_game_name text,
  p_game_console text default 'Console',
  p_game_cover text default '',
  p_completed boolean default true
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_game_id text := left(trim(coalesce(p_game_id, '')), 100);
begin
  if v_user is null then
    raise exception 'LOGIN_REQUIRED';
  end if;
  if length(v_game_id) = 0 then
    raise exception 'GAME_ID_REQUIRED';
  end if;

  insert into public.player_game_activity (
    user_id, game_id, game_name, game_console, game_cover,
    started_count, first_played_at, last_played_at, completed_at
  ) values (
    v_user,
    v_game_id,
    left(trim(coalesce(p_game_name, v_game_id)), 160),
    left(trim(coalesce(p_game_console, 'Console')), 80),
    left(trim(coalesce(p_game_cover, '')), 500),
    1,
    now(),
    now(),
    case when coalesce(p_completed, true) then now() else null end
  )
  on conflict (user_id, game_id) do update
  set game_name = excluded.game_name,
      game_console = excluded.game_console,
      game_cover = excluded.game_cover,
      started_count = greatest(public.player_game_activity.started_count, 1),
      last_played_at = now(),
      completed_at = case when coalesce(p_completed, true) then now() else null end;

  return true;
end;
$$;

revoke all on function public.retroplay_record_game_start(text, text, text, text) from public;
revoke all on function public.retroplay_set_game_completed(text, text, text, text, boolean) from public;
grant execute on function public.retroplay_record_game_start(text, text, text, text) to authenticated;
grant execute on function public.retroplay_set_game_completed(text, text, text, text, boolean) to authenticated;

notify pgrst, 'reload schema';

commit;
