-- RetroPlay Arena Online 1.0
-- Execute UMA VEZ no Supabase: SQL Editor > New query > cole tudo > Run.
-- O arquivo pode ser executado novamente sem apagar salas atuais.

begin;

create extension if not exists pgcrypto;

create table if not exists public.arena_rooms (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  game_id text not null,
  game_name text not null,
  game_console text not null default 'Console',
  game_cover text not null default '',
  host_name text not null,
  host_token uuid not null,
  guest_name text,
  guest_token uuid,
  host_ready boolean not null default false,
  guest_ready boolean not null default false,
  is_private boolean not null default true,
  status text not null default 'waiting' check (status in ('waiting', 'ready', 'playing')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '6 hours')
);

create index if not exists arena_rooms_public_idx
  on public.arena_rooms (is_private, updated_at desc);
create index if not exists arena_rooms_expires_idx
  on public.arena_rooms (expires_at);

create table if not exists public.arena_messages (
  id bigint generated by default as identity primary key,
  room_code text not null references public.arena_rooms(code) on delete cascade,
  sender_name text not null,
  message text not null,
  created_at timestamptz not null default now()
);

create index if not exists arena_messages_room_idx
  on public.arena_messages (room_code, created_at desc);

alter table public.arena_rooms enable row level security;
alter table public.arena_messages enable row level security;

-- As tabelas ficam fechadas. O site usa somente as funções abaixo.
revoke all on public.arena_rooms from anon, authenticated;
revoke all on public.arena_messages from anon, authenticated;
revoke all on sequence public.arena_messages_id_seq from anon, authenticated;

create or replace function public.arena_clean_expired()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.arena_rooms where expires_at < now();
end;
$$;

create or replace function public.arena_room_payload(
  p_room public.arena_rooms,
  p_viewer_token uuid default null
)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'code', p_room.code,
    'game_id', p_room.game_id,
    'game_name', p_room.game_name,
    'game_console', p_room.game_console,
    'game_cover', p_room.game_cover,
    'host_name', p_room.host_name,
    'guest_name', p_room.guest_name,
    'host_ready', p_room.host_ready,
    'guest_ready', p_room.guest_ready,
    'is_private', p_room.is_private,
    'status', p_room.status,
    'created_at', p_room.created_at,
    'updated_at', p_room.updated_at,
    'expires_at', p_room.expires_at,
    'viewer_role', case
      when p_viewer_token is not null and p_room.host_token = p_viewer_token then 'host'
      when p_viewer_token is not null and p_room.guest_token = p_viewer_token then 'guest'
      else ''
    end
  );
$$;

create or replace function public.arena_create_room(
  p_game_id text,
  p_game_name text,
  p_game_console text,
  p_game_cover text,
  p_host_name text,
  p_host_token uuid,
  p_is_private boolean default true
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_code text;
  v_room public.arena_rooms;
  v_tries integer := 0;
begin
  perform public.arena_clean_expired();

  if p_host_token is null then
    raise exception 'IDENTIFICACAO_INVALIDA';
  end if;
  if length(trim(coalesce(p_host_name, ''))) < 2 then
    raise exception 'DIGITE_UM_NOME';
  end if;
  if length(trim(coalesce(p_game_id, ''))) < 1 then
    raise exception 'ESCOLHA_UM_JOGO';
  end if;

  -- Um aparelho mantém apenas uma sala como anfitrião.
  delete from public.arena_rooms where host_token = p_host_token;

  loop
    v_tries := v_tries + 1;
    v_code := upper(substr(encode(gen_random_bytes(6), 'hex'), 1, 6));
    exit when not exists (select 1 from public.arena_rooms where code = v_code);
    if v_tries > 30 then
      raise exception 'NAO_FOI_POSSIVEL_GERAR_CODIGO';
    end if;
  end loop;

  insert into public.arena_rooms (
    code, game_id, game_name, game_console, game_cover,
    host_name, host_token, is_private
  ) values (
    v_code,
    left(trim(p_game_id), 80),
    left(trim(p_game_name), 120),
    left(trim(coalesce(p_game_console, 'Console')), 80),
    left(trim(coalesce(p_game_cover, '')), 500),
    left(trim(p_host_name), 24),
    p_host_token,
    coalesce(p_is_private, true)
  )
  returning * into v_room;

  return public.arena_room_payload(v_room, p_host_token);
end;
$$;

create or replace function public.arena_list_rooms()
returns setof jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.arena_clean_expired();

  return query
  select public.arena_room_payload(r, null)
  from public.arena_rooms r
  where r.is_private = false
  order by r.updated_at desc
  limit 12;
end;
$$;

create or replace function public.arena_get_room(
  p_code text,
  p_player_token uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_room public.arena_rooms;
begin
  perform public.arena_clean_expired();

  select * into v_room
  from public.arena_rooms
  where code = upper(trim(coalesce(p_code, '')))
  limit 1;

  if not found then
    return null;
  end if;

  return public.arena_room_payload(v_room, p_player_token);
end;
$$;

create or replace function public.arena_join_room(
  p_code text,
  p_guest_name text,
  p_guest_token uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_room public.arena_rooms;
begin
  perform public.arena_clean_expired();

  if p_guest_token is null then
    raise exception 'IDENTIFICACAO_INVALIDA';
  end if;
  if length(trim(coalesce(p_guest_name, ''))) < 2 then
    raise exception 'DIGITE_UM_NOME';
  end if;

  select * into v_room
  from public.arena_rooms
  where code = upper(trim(coalesce(p_code, '')))
  for update;

  if not found then
    raise exception 'SALA_NAO_ENCONTRADA';
  end if;

  if v_room.host_token = p_guest_token then
    return public.arena_room_payload(v_room, p_guest_token);
  end if;

  if v_room.guest_token = p_guest_token then
    return public.arena_room_payload(v_room, p_guest_token);
  end if;

  if v_room.guest_token is not null then
    raise exception 'SALA_CHEIA';
  end if;

  update public.arena_rooms
  set guest_name = left(trim(p_guest_name), 24),
      guest_token = p_guest_token,
      guest_ready = false,
      status = 'waiting',
      updated_at = now(),
      expires_at = now() + interval '6 hours'
  where id = v_room.id
  returning * into v_room;

  return public.arena_room_payload(v_room, p_guest_token);
end;
$$;

create or replace function public.arena_set_ready(
  p_code text,
  p_player_token uuid,
  p_ready boolean
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_room public.arena_rooms;
begin
  select * into v_room
  from public.arena_rooms
  where code = upper(trim(coalesce(p_code, '')))
  for update;

  if not found then
    raise exception 'SALA_NAO_ENCONTRADA';
  end if;

  if v_room.host_token = p_player_token then
    update public.arena_rooms set host_ready = coalesce(p_ready, false) where id = v_room.id;
  elsif v_room.guest_token = p_player_token then
    update public.arena_rooms set guest_ready = coalesce(p_ready, false) where id = v_room.id;
  else
    raise exception 'VOCE_NAO_ESTA_NESTA_SALA';
  end if;

  update public.arena_rooms
  set status = case
        when host_ready and guest_ready and guest_token is not null then 'ready'
        else 'waiting'
      end,
      updated_at = now(),
      expires_at = now() + interval '6 hours'
  where id = v_room.id
  returning * into v_room;

  return public.arena_room_payload(v_room, p_player_token);
end;
$$;

create or replace function public.arena_start_game(
  p_code text,
  p_player_token uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_room public.arena_rooms;
begin
  select * into v_room
  from public.arena_rooms
  where code = upper(trim(coalesce(p_code, '')))
  for update;

  if not found then
    raise exception 'SALA_NAO_ENCONTRADA';
  end if;
  if v_room.host_token <> p_player_token then
    raise exception 'SOMENTE_O_ANFITRIAO_PODE_INICIAR';
  end if;
  if v_room.guest_token is null or not v_room.host_ready or not v_room.guest_ready then
    raise exception 'OS_DOIS_JOGADORES_PRECISAM_ESTAR_PRONTOS';
  end if;

  update public.arena_rooms
  set status = 'playing',
      updated_at = now(),
      expires_at = now() + interval '6 hours'
  where id = v_room.id
  returning * into v_room;

  return public.arena_room_payload(v_room, p_player_token);
end;
$$;

create or replace function public.arena_leave_room(
  p_code text,
  p_player_token uuid
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_room public.arena_rooms;
begin
  select * into v_room
  from public.arena_rooms
  where code = upper(trim(coalesce(p_code, '')))
  for update;

  if not found then
    return true;
  end if;

  if v_room.host_token = p_player_token then
    delete from public.arena_rooms where id = v_room.id;
    return true;
  elsif v_room.guest_token = p_player_token then
    update public.arena_rooms
    set guest_name = null,
        guest_token = null,
        guest_ready = false,
        host_ready = false,
        status = 'waiting',
        updated_at = now(),
        expires_at = now() + interval '6 hours'
    where id = v_room.id;
    return true;
  end if;

  raise exception 'VOCE_NAO_ESTA_NESTA_SALA';
end;
$$;

create or replace function public.arena_send_message(
  p_code text,
  p_player_token uuid,
  p_message text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_room public.arena_rooms;
  v_name text;
  v_message public.arena_messages;
begin
  select * into v_room
  from public.arena_rooms
  where code = upper(trim(coalesce(p_code, '')))
  limit 1;

  if not found then
    raise exception 'SALA_NAO_ENCONTRADA';
  end if;

  if v_room.host_token = p_player_token then
    v_name := v_room.host_name;
  elsif v_room.guest_token = p_player_token then
    v_name := v_room.guest_name;
  else
    raise exception 'VOCE_NAO_ESTA_NESTA_SALA';
  end if;

  if length(trim(coalesce(p_message, ''))) < 1 then
    raise exception 'MENSAGEM_VAZIA';
  end if;

  insert into public.arena_messages (room_code, sender_name, message)
  values (v_room.code, v_name, left(trim(p_message), 240))
  returning * into v_message;

  delete from public.arena_messages
  where room_code = v_room.code
    and id not in (
      select id from public.arena_messages
      where room_code = v_room.code
      order by created_at desc
      limit 60
    );

  return jsonb_build_object(
    'id', v_message.id,
    'sender_name', v_message.sender_name,
    'message', v_message.message,
    'created_at', v_message.created_at
  );
end;
$$;

create or replace function public.arena_list_messages(
  p_code text,
  p_player_token uuid
)
returns setof jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_allowed boolean;
begin
  select exists (
    select 1 from public.arena_rooms
    where code = upper(trim(coalesce(p_code, '')))
      and (host_token = p_player_token or guest_token = p_player_token)
  ) into v_allowed;

  if not v_allowed then
    raise exception 'VOCE_NAO_ESTA_NESTA_SALA';
  end if;

  return query
  select jsonb_build_object(
    'id', m.id,
    'sender_name', m.sender_name,
    'message', m.message,
    'created_at', m.created_at
  )
  from (
    select * from public.arena_messages
    where room_code = upper(trim(coalesce(p_code, '')))
    order by created_at desc
    limit 60
  ) m
  order by m.created_at asc;
end;
$$;

revoke all on function public.arena_clean_expired() from public;
revoke all on function public.arena_room_payload(public.arena_rooms, uuid) from public;
revoke all on function public.arena_create_room(text,text,text,text,text,uuid,boolean) from public;
revoke all on function public.arena_list_rooms() from public;
revoke all on function public.arena_get_room(text,uuid) from public;
revoke all on function public.arena_join_room(text,text,uuid) from public;
revoke all on function public.arena_set_ready(text,uuid,boolean) from public;
revoke all on function public.arena_start_game(text,uuid) from public;
revoke all on function public.arena_leave_room(text,uuid) from public;
revoke all on function public.arena_send_message(text,uuid,text) from public;
revoke all on function public.arena_list_messages(text,uuid) from public;

grant execute on function public.arena_create_room(text,text,text,text,text,uuid,boolean) to anon, authenticated;
grant execute on function public.arena_list_rooms() to anon, authenticated;
grant execute on function public.arena_get_room(text,uuid) to anon, authenticated;
grant execute on function public.arena_join_room(text,text,uuid) to anon, authenticated;
grant execute on function public.arena_set_ready(text,uuid,boolean) to anon, authenticated;
grant execute on function public.arena_start_game(text,uuid) to anon, authenticated;
grant execute on function public.arena_leave_room(text,uuid) to anon, authenticated;
grant execute on function public.arena_send_message(text,uuid,text) to anon, authenticated;
grant execute on function public.arena_list_messages(text,uuid) to anon, authenticated;

commit;
